avischiffmann/Coronavirus-Dashboard

index.js, public/css/style.css, views/about.ejs, views/data.ejs, views/faq.ejs, views/map.ejs, views/partials/head.ejs, views/partials/navigation.ejs, views/partials/scripts.ejs, views/prepping.ejs, views/prevention.ejs, views/timeline.ejs, views/tweets.ejs, views/wiki.ejs
Hello! Thanks for your work!
I just made some tiny changes that use ejs' templates and partials to clean up the views a bit. 😄 
Hopefully this will make it a bit easier for you to modify the content of the pages moving forward.
I am happy to do a bit more but I thought this was a quick way to help out. 🙇‍♀
=> Using ejs to create templates for header, footer, scripts, head.

views/about.ejs, views/data.ejs, views/faq.ejs, views/map.ejs, views/prepping.ejs, views/timeline.ejs, views/tweets.ejs, views/wiki.ejs
The head partial should really be the scripts partial. This fixes the mobile navigation.
=> Head should be scripts

public/css/style.css, syncData.js, views/data.ejs
Adding a recovery progress bar to each region.
=> Progress bar

public/css/style.css, views/data.ejs, views/partials/head.ejs
=> Hide recovered on mobile

views/about.ejs
=> Typo fix in the classname

views/data.ejs
Disable rows expanding to show extra data.
=> Disable row expanding

views/partials/head.ejs
Adding metadata for twitter so it looks nicer. 🎨 Was requested by lots on twitter.
=> Adding twitter meta data

package.json
Let's not be those guys. 😅 It's not a published package so you won't have to do anything after this change.
=> Changing the package name.

index.js, views/data.ejs
=> Adding in Latin America and Australia

public/css/style.css, views/data.ejs
Quick at lunch update to make the meters responsive.
=> Make meters responsive and fix css

views/data.ejs
=> Adding twitter for support eng.

syncData.js
Totally a patch. Needs to be reworked but I am sick. 😷
=> Sync between global and europe

syncData.js
Recalcs the sorted EU data so the Total row is accurate.
=> Recalc the EU total. Should do this for all later.

globals.js
We should completely fill this out at some point. Shoutout to (iBHRPr0cCAfoQak) on twitter for aggregating this!
=> Adding some EU countries that were missing or mis-labeled

globals.js, index.js, micro-scrapers/coronatracker.js, syncData.js, utilities.js, views/data.ejs
* Fix serious' sorting.
* Always use highest value from either source.
=> Always pick key with highest value. Serious sorts properly

utilities.js
=> Typo in length name

fetchData.js, globals.js, micro-scrapers/bno.js, utilities.js
Finalllyy!!!! Syncing countries that have multiple different labels/names between Global and their Region list.
I also synced USA and Global! Feelsgoodman.jpg
=> Countries with multiple names should sync. USA syncs.

overrides/statistics_LatinAmerica.json
Burned by my own working code 🤣
=> Don't override Latin America's totals

fetchData.js, globals.js, micro-scrapers/bno.js, micro-scrapers/coronatracker.js, utilities.js
* Extract label-renamer into utilities.
* Add a few countries to be relabeled.
* Don't recalculate totals every call because it happens at the end.
This will sync Latin America's data with Global 👍
=> Adding more countries to be relabeled

public/css/style.css, views/data.ejs, views/partials/navigation.ejs
I added a mobile nav! 🖌 🎨 
**ONLY MERGE AFTER YOU PULL IT DOWN AND TRY IT**
=> Making a mobile navigation

public/css/style.css, views/data.ejs
Really just needs to be tested out a bit. I am going to try it out on my iPad mini and iPhone.
iPhone seemed to work great.
=> Re-doing mobile view so more data can be displayed

public/css/style.css, views/data.ejs
Diff. set of tables for mobile. Just pushing up the bit of work from last night 👍
=> Quick restructure for mobile tables. Uses different set on mobile now.

micro-scrapers/bno.js
Avoid BNO setting N/A as a value. Will need to move this into the util function.
=> Removing N/A from filter

micro-scrapers/bno.js, utilities.js, views/data.ejs
Don't always sort by cases in mobile nav.
=> Sort mobile

micro-scrapers/bno.js, utilities.js
Okay I actually had already prepared for this happening but forgot about it in the rush of things 😅
=> More permanent solution to earliers emergency N/A as a value

micro-scrapers/bno.js
=> Removing N/A BNO

views/partials/head.ejs
=> Cache bust the CSS

views/data.ejs
Mobile is too looong. Scroll global section.
=> Scroll for global on mobile

fetchData.js, index.js, micro-scrapers/bno.js
=> Don't sync data if missing keys.

globals.js, index.js, scraper.js
After this is merged we need to do a:
`pm2 restart all` and `pm2 start scraper.js`
=> Seperate scraper

fetchData.js, micro-scrapers/bno.js, micro-scrapers/thevirustracker/graph.js, package-lock.json, scraper.js
Hooray I found a much better CSV parser. This one won't require us to store a tmp/ .csv file anymore. I'll remove those in a follow-up PR.
You only need to restart the scraper, not the express cluster. 👍
=> Catch csv errors

fetchData.js, views/data.ejs
=> Updating US total after sync. Changing label.

fetchData.js
Hide global % until we can calibrate with all regions %.
=> Hide global change until we can calibrate

views/data.ejs
=> Left-align data on mobile

fetchData.js, micro-scrapers/bno.js, scraper.js, syncData.js, utilities.js, views/data.ejs
* Show rate based on increase in death count, not total cases. Much scarier number. 😭 
* Add a site-update.
=> Calculate death rate based on death count not case count

fetchData.js, micro-scrapers/bno.js
BNO is throwing huge amounts of undocumented cases. Ignore them and fallback to their explicit total.
=> Trust BNO for global total.

fetchData.js, utilities.js, views/data.ejs
Override ability per region and country.
=> Don't sync the country georgia with the state georgia

views/data.ejs
I changed the timezone under the Site Update section to reflect Daylight Savings Time where EST is now EDT.
=> Changed EST to EDT under Site Update

globals.js, utilities.js, views/data.ejs
Decided why not after all but we'll see.  🐦 💬
=> Adding twitter

syncData.js, utilities.js
If something was exactly a match it would truncate.
=> prevent truncating 100s

fetchData.js, public/css/style.css, views/data.ejs
Now when the page loads the flash isnt as jarring. Didn't do it for mobile yet tho.
=> Make desktop styles match datables styles to reduce flash

globals.js
=> Relabel UK and S Korea

views/coronainfo.ejs
=> Remove broken image.
